# Site settings
title: Test site
email: your-email@domain.com
description: "This is a test site for testing how to work with jekyll."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
