# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Passing Thoughts
email: lee+blog@elenbaas.org.il
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://passing-thoughts.lee-elenbaas.github.io/" # the base hostname & protocol for your site
author: "Lee Elenbaas"

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
paginate: 5
paginate_path: 'page:num/'
include: ['_posts']
comments: true
excerpt_separator: <!-- more -->
